name: Build and Deploy
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download theme
        uses: actions/checkout@v2
        with:
          repository: ress997/hugo-robust
          path: themes/robust

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Save /public
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public

  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load /public
        uses: actions/download-artifact@v1
        with:
          name: public

      - name: Optimize AMP
        uses: asurbernardo/amp-optimizer-action@1.0.2
        with:
          root: 'public/amp'

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
